name: chavocontrol_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # PAQUETE PARA GENERAR ICONOS:
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# CONFIGURACIÓN DEL ICONO DE LA APLICACIÓN
# ----------------------------------------
flutter_icons:
  # 1. RUTA DE LA IMAGEN: Asegúrate de que tu archivo de icono (idealmente 512x512px)
  #    esté en esta ubicación (e.g., assets/images/app_icon.png)
  image_path: "assets/images/Icon_ChavoControl.png"

  # 2. PLATAFORMAS: Genera iconos para Android e iOS
  android: true
  ios: true

  # 3. OPCIONAL: Si quieres usar Adaptive Icons para Android (Recomendado)
  # adaptive_icon_background: "#FFFFFF"  # Color o ruta de imagen para el fondo
  # adaptive_icon_foreground: "assets/images/mi_icono_foreground.png" # Imagen para el primer plano (sin fondo)